### ISSUE TITLE
Better panning

### ISSUE THREAD

**Issue by simonthalen** [philstopford/etoViewport#34]
Hello and thank you for your awesome work with Eto.OpenTK. I use it alot. 

I found your implementation of panning to be very sluggish. Especially considering zooming works very well. I made the following improvements to the dragHandler function in the TestViewport class:

```
float new_X = (ovpSettings.cameraPosition.X - (((float)e.Location.X - x_orig) * ovpSettings.zoomFactor)); 
float new_Y = (ovpSettings.cameraPosition.Y + (((float)e.Location.Y - y_orig) * ovpSettings.zoomFactor));
ovpSettings.cameraPosition = new PointF(new_X, new_Y);
x_orig = e.Location.X;
y_orig = e.Location.Y;
```

Simply exchanging the arbitray scaling factor in new_X and new_Y for ovpSettings.zoomFactor and updating x_orig and y_orig gives panning a feeling of moving a surface with the mouse. Much more pleasant!

Thank you

**Comment by philstopford** [comment]
This works nicely - I have it implemented in my fork of Eto.OpenTK and would support this change in upstream.
