### ISSUE TITLE
XamMac: breaks when compiling with VisualStudio for Mac 

### ISSUE THREAD

**Issue by joa77** [philstopford/etoViewport#9]
When I'm trying to start the project with the lastest VisualStudio for Mac the XamMac part won't work.
The MonoMac project still works perfect.

The exeption raises in `MacGLView8.cs` in Line 95: `context = new GraphicsContext(mode, windowInfo, major, minor, flags);`
It's an `OpenTK.Graphics.GraphicsContextException`: `The specified window isn't an OpenGL window`

**Comment by philstopford** [comment]
I don't yet have a Mac handy for this. My workhorse died and was replaced with a PC. I'll take a look when I am able.

**Comment by philstopford** [comment]
I expect this is fixed with the recent work from Curtis, so will close this ticket.
